### ISSUE TITLE
你好，如果“tv_chart_container”这个DIV下再加一个交易对列表，然后点击交易对，可以不刷新页面直接更改蜡烛图吗

### ISSUE THREAD

**Issue by yutou303** [No2015/tradingview-websocket#1]
> <div id="tv_chart_container" style="height: 530px"></div>

        <ul id="symbolName">
            <li data-symbol="btcusdt">BTC/USDT</li>
            <li data-symbol="ethusdt">ETHUSDT</li>
            <li data-symbol="eosusdt">EOS/USDT</li>
            <li data-symbol="xrpusdt">XRP/USDT</li>
            <li data-symbol="ltcusdt">LTC/USDT</li>
        </ul>

**Comment by No2015** [comment]
可以的啊，setSymbol方法。
你可以查看图表插件对象的内置方法，便利出来就可以了：
for(var i in _TVjsApi.widgets.chart()){console.log(i)}
这个widgets.chart()是图表插件调用api的接口，demo中提供了_TVjsApi对象暴露出来。

**Comment by No2015** [comment]
需要修改默认商品参数，在/js/datafees.js的末尾，把商品的名称改为自动获取：this.self.symbol.toLocaleUpperCase()，
然后在change的时候修改symbol：_TVjsApi.symbol = symbol
同时触发图表的变化：_TVjsApi.widgets.chart().setSymbol(symbol.toLocaleUpperCase());
demo已经修改，可以查看最新的commit，
widgets.chart()这个方法是图表调用API的接口，可以遍历chart来查看图表的API源码：
for(var api in _TVjsApi.widgets.chart()){ console.log(api) }
或者查看[手册](https://zlq4863947.gitbooks.io/tradingview/book/Widget-Methods.html)

**Comment by yutou303** [comment]
666...... 上午没事也试着修改TVjsApi.js里的 symbol ，但就没有考虑到 datafees.js 里也要改。。

很棒！！！这样以后应该会用到。。 ☺☺

**Comment by No2015** [comment]
> 666...... 上午没事也试着修改TVjsApi.js里的 symbol ，但就没有考虑到 datafees.js 里也要改。。
> 
> 很棒！！！这样以后应该会用到。。 ☺☺

但是修改商品之后，需要取消订阅，缓存清除，demo中没有实现这部分功能的，你可以在getBars方法中做判断。
