### ISSUE TITLE
vue如何使用？

### ISSUE THREAD

**Issue by guoyoujin** [No2015/tradingview-websocket#2]
vue 使用的时候一直报下面这个错误

```
charting_library.min.js:1 Uncaught TypeError: i.contentWindow.widgetReady is not a function
    at HTMLIFrameElement.n (charting_library.min.js:1)
```

**Comment by No2015** [comment]
似乎是你初始化的时候，图表元素处在不可见状态，获取不到iframe窗口

**Comment by guoyoujin** [comment]
嗯，是的，放在```mounted()```里面执行就行啦，谢谢啦，

另外问下，假如我不是websocket，而是一个api接口，每隔几分钟自动请求，怎么样实现这个功能更好，我现在已经改成http的api接口模式了，但是发现在切换顶部的button时间率选的时候，数据不刷新，是否是因为 ```cacheData```

**Comment by No2015** [comment]
> 嗯，是的，放在`mounted()`里面执行就行啦，谢谢啦，
> 
> 另外问下，假如我不是websocket，而是一个api接口，每隔几分钟自动请求，怎么样实现这个功能更好，我现在已经改成http的api接口模式了，但是发现在切换顶部的button时间率选的时候，数据不刷新，是否是因为 `cacheData`

如果是切换时间颗粒的时候没有触发数据更新，有两个可能。
一个是没有修改resolution参数，这样图表插件调用getBars的时候没有用新的resolution来发起调用。
另一个就是修改了resolution，但是在图表插件调用getBars的时候没有重新发起订阅。
你可以在getBars那儿控制台输出一下
```
getBars(symbolInfo, resolution, rangeStartDate, rangeEndDate, onLoadedCallback) {
            //console.log(' >> :', rangeStartDate, rangeEndDate)
            resolution = localStorage.getItem('tradingview.resolution') || 5
            //只能通过tradingview.resolution获取时间颗粒，因为getBars的时间颗粒最多只有天，但是我们的插件可以到月
            //console.log(' >> :', this.interval, resolution)
```
如果一切正常，可能是cacheData的原因，你可以每次切换的时候把cacheData清空试试

**Comment by guoyoujin** [comment]
好的，👌，谢谢啦🙏🙏
