### ISSUE TITLE
调用resetTheme的时候会抛出异常

### ISSUE THREAD

**Issue by madcodelife** [No2015/tradingview-websocket#3]
![image](https://user-images.githubusercontent.com/28998859/60379754-10782c00-9a6b-11e9-89c5-2218566b1c2c.png)

**Comment by No2015** [comment]
如果我没记错的话，这个错误是resetTheme执行的时候，其他资源还没有载入。

**Comment by madcodelife** [comment]
解决了 确实是资源没有加载完 谢谢
